{% set name = "apricot-select" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jmschrei/{{ name|replace('-select', '') }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 595b7a1a180d939e0ce9d27d6fb4d4988c054bc0e0a80362ab3aadaa35918a98

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - numpy >=1.14.2
    - scipy >=1.0.0
    - numba >=0.43.0
    - tqdm >=4.24.0
    - nose
    # https://github.com/jmschrei/apricot/issues/39#issuecomment-1708080169
    - scikit-learn >=0.22

# Exclude tests issue: ValueError: Unable to avoid copy while creating an array as requested.
# If using `np.array(obj, copy=False)` replace it with `np.asarray(obj)` to allow a copy when needed (no behavior change in NumPy 1.x).
# For more details, see https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword.
{% set ignore_tests = " --ignore=tests/test_functions/test_mixture_feature_based.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/test_functions/test_mixture_graph_based.py" %}
# ModuleNotFoundError: No module named 'imp'
{% set ignore_tests = ignore_tests + " --ignore=tests/test_optimizers/test_knapsack_feature_based.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/test_optimizers/test_knapsack_facility_location.py" %}
# AssertionError: Arrays are not equal
{% set ignore_tests = ignore_tests + " --ignore=tests/test_functions/test_max_coverage.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/test_functions/test_sum_redundancy.py" %}

test:
  source_files:
    - tests
  imports:
    - apricot
    - apricot.optimizers
    - apricot.utils
    - apricot.functions
    - apricot.functions.base
    - apricot.functions.custom
    - apricot.functions.facilityLocation
    - apricot.functions.featureBased
    - apricot.functions.graphCut
    - apricot.functions.maxCoverage
    - apricot.functions.mixture
    - apricot.functions.saturatedCoverage
    - apricot.functions.sumRedundancy
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest {{ ignore_tests }}
  requires:
    - pip
    - pytest
    - pytorch

about:
  home: https://github.com/jmschrei/apricot
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: apricot is a package for submodular optimization brought to you in a convenient sklearn-like format.
  description: apricot is a package for submodular optimization brought to you in a convenient sklearn-like format.
    The package focuses on (1) being flexible enough for allow users to easily define their own functions and optimizers
    just as you can in neural network libraries, and (2) being fast by using numba to speed up the computationally intensive aspects.
  doc_url: https://apricot-select.readthedocs.io
  dev_url: https://github.com/jmschrei/apricot

extra:
  recipe-maintainers:
    - tschuelia
